In [1]:
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import os
import pandas as pd
import glob
import numpy as np

In [2]:
path = '/uscms/home/jieun201/nobackup/YOURWORKINGAREA/june23_ds8_labelsOnly'
csv_files = glob.glob(path + "/*.csv")
df_labels = (pd.read_csv(file) for file in csv_files)
big_df_labels   = pd.concat(df_labels, ignore_index=True)
path = '/uscms/home/jieun201/nobackup/YOURWORKINGAREA/june23_ds8_negativeLabelsOnly'
csv_files2 = glob.glob(path + "/*.csv")
df_labels2 = (pd.read_csv(file) for file in csv_files2)
big_df_labels2   = pd.concat(df_labels2, ignore_index=True)
mergePosNeg = pd.concat([big_df_labels, big_df_labels2])
s = pd.Series(mergePosNeg['pt'])
BigSampleValueCounts = s.value_counts(bins=[-2.0,-1.9,-1.8,-1.7,-1.6,-1.5,-1.4,-1.3,-1.2,-1.1,-1.0,-0.9,-0.8,-0.7,-0.6,-0.5,
                                              -0.4,-0.3,-0.2,-0.1,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,
                                              1.5,1.6,1.7,1.8,1.9,2.0]).sort_index()
BigSampleValueCounts

(-2.001, -1.9]     22898
(-1.9, -1.8]       27127
(-1.8, -1.7]       32528
(-1.7, -1.6]       39104
(-1.6, -1.5]       47190
(-1.5, -1.4]       56900
(-1.4, -1.3]       69910
(-1.3, -1.2]       85706
(-1.2, -1.1]      105326
(-1.1, -1.0]      130359
(-1.0, -0.9]      165607
(-0.9, -0.8]      198763
(-0.8, -0.7]      256822
(-0.7, -0.6]      323231
(-0.6, -0.5]      399458
(-0.5, -0.4]      490657
(-0.4, -0.3]      565226
(-0.3, -0.2]      587652
(-0.2, -0.1]      203420
(-0.1, 0.0]          380
(0.0, 0.1]           380
(0.1, 0.2]        216509
(0.2, 0.3]        623085
(0.3, 0.4]        592413
(0.4, 0.5]        505111
(0.5, 0.6]        408333
(0.6, 0.7]        326467
(0.7, 0.8]        259269
(0.8, 0.9]        200540
(0.9, 1.0]        166169
(1.0, 1.1]        131131
(1.1, 1.2]        105435
(1.2, 1.3]         85022
(1.3, 1.4]         69922
(1.4, 1.5]         57426
(1.5, 1.6]         47443
(1.6, 1.7]         39366
(1.7, 1.8]         32326
(1.8, 1.9]         27757
(1.9, 2.0]         22776


In [3]:
TruthTotalCounts = np.array(BigSampleValueCounts)
Total_TruthTotalCounts = np.sum(TruthTotalCounts)
Total_TruthTotalCounts

7725144

In [4]:
df1 = pd.read_csv('/uscms/home/jieun201/nobackup/YOURWORKINGAREA/dec6_ds8/TestSetTruePT.csv')
df2 = pd.read_csv('/home/jieun201/redo_dec6_dec8_FP/predictionsFiles.csv')
df3 = pd.read_csv('/home/jieun201/redo_dec6_dec8_FP/true.csv')
df2.columns.values[0] = "predict"
df3.columns.values[0] = "true"
df2['predict'] = df2['predict'].astype(int)
concatenate = pd.concat([df1,df2, df3], axis=1)
s2 = pd.Series(concatenate['pt'])  
BigSampleValueCounts2 = s2.value_counts(bins=[-2.0,-1.9,-1.8,-1.7,-1.6,-1.5,-1.4,-1.3,-1.2,-1.1,-1.0,-0.9,-0.8,-0.7,-0.6,-0.5,
                                              -0.4,-0.3,-0.2,-0.1,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,
                                              1.5,1.6,1.7,1.8,1.9,2.0]).sort_index()
testSetTotalCounts = np.array(BigSampleValueCounts2)
testSetTotalCounts

array([  235,   279,   353,   452,   566,   606,   808,   908,  1157,
        1447,  1779,  2100,  2797,  3306,  4435,  5401,  6170,  6516,
       40674,    86,    82, 40678,  6706,  6404,  5383,  4182,  3395,
        2762,  2133,  1759,  1396,  1123,   906,   781,   610,   495,
         442,   349,   303,   254])

In [5]:
denominator = concatenate.loc[ (concatenate['pt'] < 2) & (concatenate['pt'] > -2.0)]
denominator

pt  predict  true
1       0.195180        2     2
2       1.338710        2     0
3       0.180981        2     2
4       0.457629        0     0
5       0.283597        2     0
...          ...      ...   ...
163035  0.395177        2     0
163036 -0.164451        1     1
163037 -0.456705        1     0
163038 -0.168745        0     1
163039  0.124187        2     2

[160218 rows x 3 columns]

In [6]:
PredictRight = denominator[(denominator['predict'] ==1) | (denominator['predict'] ==2)]
PredictRight

pt  predict  true
1       0.195180        2     2
2       1.338710        2     0
3       0.180981        2     2
5       0.283597        2     0
6      -0.314178        1     0
...          ...      ...   ...
163034 -0.199993        1     1
163035  0.395177        2     0
163036 -0.164451        1     1
163037 -0.456705        1     0
163039  0.124187        2     2

[77571 rows x 3 columns]

In [7]:
s3 = pd.Series(PredictRight['pt'])
BigSampleValueCounts3 = s3.value_counts(bins=[-2.0,-1.9,-1.8,-1.7,-1.6,-1.5,-1.4,-1.3,-1.2,-1.1,-1.0,-0.9,-0.8,-0.7,-0.6,-0.5,
                                              -0.4,-0.3,-0.2,-0.1,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,
                                              1.5,1.6,1.7,1.8,1.9,2.0]).sort_index()
testSetAs12 = np.array(BigSampleValueCounts3)
testSetAs12 #1,2 meaning the labels

array([   23,    28,    27,    32,    38,    61,    57,    68,   127,
         123,   153,   221,   311,   446,   665,  1066,  1706,  2864,
       27710,    78,    80, 32074,  3637,  2165,  1245,   731,   472,
         314,   243,   195,   146,   108,    78,    71,    54,    35,
          39,    24,    29,    27])

In [8]:
makeRatio = TruthTotalCounts/testSetTotalCounts
makeRatio


array([97.43829787, 97.22939068, 92.14730878, 86.51327434, 83.3745583 ,
       93.89438944, 86.52227723, 94.38986784, 91.03370787, 90.08914997,
       93.08993817, 94.64904762, 91.82052199, 97.77102238, 90.06944758,
       90.84558415, 91.60875203, 90.18600368,  5.00122929,  4.41860465,
        4.63414634,  5.32250848, 92.91455413, 92.50671455, 93.83447892,
       97.64060258, 96.16111929, 93.87002172, 94.01781528, 94.46787948,
       93.93338109, 93.88691006, 93.84326711, 89.52880922, 94.14098361,
       95.84444444, 89.06334842, 92.62464183, 91.60726073, 89.66929134])

In [9]:
Sum = np.dot(testSetAs12,makeRatio)
Sum

1941038.856859268

In [10]:
Sum/Total_TruthTotalCounts

0.2512624822086511