In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas import read_csv
import math
import seaborn as sns

In [2]:
df1 = pd.read_csv('/uscms/home/jieun201/nobackup/YOURWORKINGAREA/dec6_ds8/TestSetTruePT.csv')
df2 = pd.read_csv('predictionsFiles.csv')
df3 = pd.read_csv('true.csv')
df2.columns.values[0] = "predict"
df3.columns.values[0] = "true"
df2['predict'] = df2['predict'].astype(int)

In [3]:
concatenate = pd.concat([df1,df2, df3], axis=1)

In [4]:
list1 = [] #this holds the number of entries in each bin
list2 = [] #this holds the value, here counts how many entries are predicted as "0"

In [5]:
binValidate1 = concatenate.loc[(concatenate['pt'] > -0.1) & (concatenate['pt'] <= 0.0)]
list1.append(binValidate1.shape[0])
list2.append( sum((binValidate1.predict == 0))/(binValidate1.shape[0]) )

binValidate2 = concatenate.loc[(concatenate['pt'] > -0.2) & (concatenate['pt'] <= -0.1)]
list1.append(binValidate1.shape[0])
list2.append( sum((binValidate2.predict == 0))/(binValidate2.shape[0]) )

binValidate3 = concatenate.loc[(concatenate['pt'] >-0.3) & (concatenate['pt'] <= -0.2)]
list1.append( binValidate3.shape[0])
list2.append( sum((binValidate3.predict == 0))/(binValidate3.shape[0]) )

In [6]:
bin4 = concatenate.loc[  ((concatenate['pt'] > -0.4) & (concatenate['pt'] <= -0.3)  )       ]
list1.append(bin4.shape[0])
list2.append( sum((bin4.predict == 0))/(bin4.shape[0]))

In [7]:
bin5 = concatenate.loc[  ((concatenate['pt'] > -0.5) & (concatenate['pt'] <= -0.4)  )] 
list1.append(bin5.shape[0])
list2.append( sum((bin5.predict == 0))/(bin5.shape[0]))

In [8]:
bin6 = concatenate.loc[ ( (concatenate['pt'] > -0.6) & (concatenate['pt'] <= -0.5)   )]
#bin6 = concatenate.loc[(concatenate['pt'] < 0.6) & (concatenate['pt'] >= 0.5)]
list1.append(bin6.shape[0])
list2.append( sum((bin6.predict == 0))/(bin6.shape[0]) )

In [9]:
bin7 = concatenate.loc[  ( (concatenate['pt'] > -0.7) & (concatenate['pt'] <= -0.6)   )] 
#bin7 = concatenate.loc[(concatenate['pt'] < 0.7) & (concatenate['pt'] >= 0.6)]
list1.append(bin7.shape[0])
list2.append( sum((bin7.predict == 0))/(bin7.shape[0]) )

In [10]:
bin8 = concatenate.loc[  ( (concatenate['pt'] > -0.8) & (concatenate['pt'] <= -0.7)    )]
#bin8 = concatenate.loc[(concatenate['pt'] < 0.8) & (concatenate['pt'] >= 0.7)]
list1.append(bin8.shape[0])
list2.append( sum((bin8.predict == 0))/(bin8.shape[0]) )

In [11]:
bin9 = concatenate.loc[  ( (concatenate['pt'] > -0.9) & (concatenate['pt'] <= -0.8)   )] 
#bin9 = concatenate.loc[(concatenate['pt'] < 0.9) & (concatenate['pt'] >= 0.8)]
list1.append(bin9.shape[0])
list2.append( sum((bin9.predict == 0))/(bin9.shape[0]) )

In [12]:
bin10 = concatenate.loc[  ( (concatenate['pt'] > -1.0) & (concatenate['pt'] <= -0.9)    )]
#bin10 = concatenate.loc[(concatenate['pt'] < 1.0) & (concatenate['pt'] >= 0.9)]
list1.append(bin10.shape[0])
list2.append( sum((bin10.predict == 0))/(bin10.shape[0]) )

In [13]:
bin11 = concatenate.loc[  ( (concatenate['pt'] > -1.1) & (concatenate['pt'] <= -1.0)    )]
#bin11 = concatenate.loc[(concatenate['pt'] < 1.1) & (concatenate['pt'] >= 1.0)]
list1.append(bin11.shape[0])
list2.append( sum((bin11.predict == 0))/(bin11.shape[0]) )

In [14]:
bin12 = concatenate.loc[  ( (concatenate['pt'] > -1.2) & (concatenate['pt'] <= -1.1)    )]
#bin12 = concatenate.loc[(concatenate['pt'] < 1.2) & (concatenate['pt'] >= 1.1)]
list1.append(bin12.shape[0])
list2.append( sum((bin12.predict == 0))/(bin12.shape[0]) )

In [15]:
bin13 = concatenate.loc[  ( (concatenate['pt'] > -1.3) & (concatenate['pt'] <= -1.2)    )]
#bin13 = concatenate.loc[(concatenate['pt'] < 1.3) & (concatenate['pt'] >= 1.2)]
list1.append(bin13.shape[0])
list2.append( sum((bin13.predict == 0))/(bin13.shape[0]) )

In [16]:
bin14 = concatenate.loc[  ( (concatenate['pt'] > -1.4) & (concatenate['pt'] <= -1.3)    )]
#bin14 = concatenate.loc[(concatenate['pt'] < 1.4) & (concatenate['pt'] >= 1.3)]
list1.append(bin14.shape[0])
list2.append( sum((bin14.predict == 0))/(bin14.shape[0]) )

In [17]:
bin15 = concatenate.loc[ ( (concatenate['pt'] > -1.5) & (concatenate['pt'] <= -1.4)   )] 
#bin15 = concatenate.loc[(concatenate['pt'] < 1.5) & (concatenate['pt'] >= 1.4)]
list1.append(bin15.shape[0])
list2.append( sum((bin15.predict == 0))/(bin15.shape[0]) )

In [18]:
bin16 = concatenate.loc[  ( (concatenate['pt'] > -1.6) & (concatenate['pt'] <= -1.5)   )] 
#bin16 = concatenate.loc[(concatenate['pt'] < 1.6) & (concatenate['pt'] >= 1.5)]
list1.append(bin16.shape[0])
list2.append( sum((bin16.predict == 0))/(bin16.shape[0]) )

In [19]:
bin17 = concatenate.loc[  ( (concatenate['pt'] > -1.7) & (concatenate['pt'] <= -1.6)    )]
#bin17 = concatenate.loc[(concatenate['pt'] < 1.7) & (concatenate['pt'] >= 1.6)]
list1.append(bin17.shape[0])
list2.append( sum((bin17.predict == 0))/(bin17.shape[0]) )

In [20]:
bin18 = concatenate.loc[  ( (concatenate['pt'] > -1.8) & (concatenate['pt'] <= -1.7)    )]
#bin18 = concatenate.loc[(concatenate['pt'] < 1.8) & (concatenate['pt'] >= 1.7)]
list1.append(bin18.shape[0])
list2.append( sum((bin18.predict == 0))/(bin18.shape[0]) )

In [21]:
bin19 = concatenate.loc[ ( (concatenate['pt'] > -1.9) & (concatenate['pt'] <= -1.8)   )] 
#bin19 = concatenate.loc[(concatenate['pt'] < 1.9) & (concatenate['pt'] >= 1.8)]
list1.append(bin19.shape[0])
list2.append( sum((bin19.predict == 0))/(bin19.shape[0]) )

In [22]:
bin20 = concatenate.loc[ ( (concatenate['pt'] > -2.0) & (concatenate['pt'] <= -1.9)    )]
#bin20 = concatenate.loc[(concatenate['pt'] < 2.0) & (concatenate['pt'] >= 1.9)]
list1.append(bin20.shape[0])
list2.append( sum((bin20.predict == 0))/(bin20.shape[0]) )

In [23]:
bin21 = concatenate.loc[  ( (concatenate['pt'] > -2.1) & (concatenate['pt'] <= -2.0)    )]
bin22 = concatenate.loc[  ( (concatenate['pt'] > -2.2) & (concatenate['pt'] <= -2.1)    )]
bin23 = concatenate.loc[  ( (concatenate['pt'] > -2.3) & (concatenate['pt'] <= -2.2)    )]
bin24 = concatenate.loc[ ( (concatenate['pt'] > -2.4) & (concatenate['pt'] <= -2.3)    )]
bin25 = concatenate.loc[  ( (concatenate['pt'] > -2.5) & (concatenate['pt'] <= -2.4)    )]
bin21_25 = bin21.shape[0] + bin22.shape[0]+ bin23.shape[0] + bin24.shape[0]+ bin25.shape[0]
list1.append(bin21_25)
list2.append((sum(bin21.predict == 0) +sum(bin22.predict == 0) + sum(bin23.predict == 0) + sum(bin24.predict == 0) + sum(bin25.predict == 0))/bin21_25) 

In [24]:
bin26 = concatenate.loc[  ( (concatenate['pt'] > -2.6) & (concatenate['pt'] <= -2.5)    )]
bin27 = concatenate.loc[  ( (concatenate['pt'] > -2.7) & (concatenate['pt'] <= -2.6)    )]
bin28 = concatenate.loc[  ( (concatenate['pt'] > -2.8) & (concatenate['pt'] <= -2.7)    )]
bin29 = concatenate.loc[   ( (concatenate['pt'] > -2.9) & (concatenate['pt'] <= -2.8)    )]
bin30 = concatenate.loc[  ( (concatenate['pt'] > -3.0) & (concatenate['pt'] <= -2.9)    )]
bin26_30 = bin26.shape[0] + bin27.shape[0]+ bin28.shape[0] + bin29.shape[0]+ bin30.shape[0]
list1.append(bin26_30)
list2.append((sum(bin26.predict == 0) +sum(bin27.predict == 0) + sum(bin28.predict == 0) + sum(bin29.predict == 0) + sum(bin30.predict == 0))/bin26_30) 

In [25]:
bin31 = concatenate.loc[  ( (concatenate['pt'] > -3.1) & (concatenate['pt'] <= -3.0)    )]
bin32 = concatenate.loc[  ( (concatenate['pt'] > -3.2) & (concatenate['pt'] <= -3.1)    )]
bin33 = concatenate.loc[   ( (concatenate['pt'] > -3.3) & (concatenate['pt'] <= -3.2)    )]
bin34 = concatenate.loc[  ( (concatenate['pt'] > -3.4) & (concatenate['pt'] <= -3.3)    )]
bin35 = concatenate.loc[  ( (concatenate['pt'] > -3.5) & (concatenate['pt'] <= -3.4)    )]
bin31_35 = bin31.shape[0] + bin32.shape[0]+ bin33.shape[0] + bin34.shape[0]+ bin35.shape[0]
list1.append(bin31_35)
list2.append((sum(bin31.predict == 0) +sum(bin32.predict == 0) + sum(bin33.predict == 0) + sum(bin34.predict == 0) + sum(bin35.predict == 0))/bin31_35 ) 

In [26]:
bin36 = concatenate.loc[  ( (concatenate['pt'] > -3.6) & (concatenate['pt'] <= -3.5)    )]
bin37 = concatenate.loc[  ( (concatenate['pt'] > -3.7) & (concatenate['pt'] <= -3.6)    )]
bin38 = concatenate.loc[ ( (concatenate['pt'] > -3.8) & (concatenate['pt'] <= -3.7)    )]
bin39 = concatenate.loc[   ( (concatenate['pt'] > -3.9) & (concatenate['pt'] <= -3.8)    )]
bin40 = concatenate.loc[ ( (concatenate['pt'] > -4.0) & (concatenate['pt'] <= -3.9)    )]
bin36_40 = bin36.shape[0] + bin37.shape[0]+ bin38.shape[0] + bin39.shape[0]+ bin40.shape[0]
list1.append(bin36_40)
list2.append((sum(bin36.predict == 0) +sum(bin37.predict == 0) + sum(bin38.predict == 0) + sum(bin39.predict == 0) + sum(bin40.predict == 0))/bin36_40 ) 

In [27]:
bin41 = concatenate.loc[  ( (concatenate['pt'] > -4.1) & (concatenate['pt'] <= -4.0)    )]
bin42 = concatenate.loc[   ( (concatenate['pt'] > -4.2) & (concatenate['pt'] <= -4.1)    )]
bin43 = concatenate.loc[   ( (concatenate['pt'] > -4.3) & (concatenate['pt'] <= -4.2)    )]
bin44 = concatenate.loc[   ( (concatenate['pt'] > -4.4) & (concatenate['pt'] <= -4.3)  )]
bin45 = concatenate.loc[   ( (concatenate['pt'] > -4.5) & (concatenate['pt'] <= -4.4)    )]
bin41_45 = bin41.shape[0] + bin42.shape[0]+ bin43.shape[0] + bin44.shape[0]+ bin45.shape[0] 
list1.append(bin41_45)
list2.append((sum(bin41.predict == 0) +sum(bin42.predict == 0) + sum(bin43.predict == 0) + sum(bin44.predict == 0) + sum(bin45.predict == 0))/bin41_45 ) 

In [28]:
bin46 = concatenate.loc[   ( (concatenate['pt'] > -4.6) & (concatenate['pt'] <= -4.5)    )]
bin47 = concatenate.loc[  ( (concatenate['pt'] > -4.7) & (concatenate['pt'] <= -4.6)    )]
bin48 = concatenate.loc[   ( (concatenate['pt'] > -4.8) & (concatenate['pt'] <= -4.7)    )]
bin49 = concatenate.loc[   ( (concatenate['pt'] > -4.9) & (concatenate['pt'] <= -4.8)    )]
bin50 = concatenate.loc[ ( (concatenate['pt'] > -5.0) & (concatenate['pt'] <= -4.9)    )]
bin46_50 = bin46.shape[0] + bin47.shape[0]+ bin48.shape[0] + bin49.shape[0]+ bin50.shape[0]  
list1.append(bin46_50)
list2.append((sum(bin46.predict == 0) +sum(bin47.predict == 0) + sum(bin48.predict == 0) + sum(bin49.predict == 0) + sum(bin50.predict == 0))/bin46_50 ) 

In [29]:
reversed_list2 = list2[::-1]
#reversed_list2

In [30]:
len(reversed_list2)

26

In [31]:
xvalues = [-0.1,-0.2,-0.3,-0.4,-0.5,-0.6,-0.7,-0.8,-0.9,-1.0,-1.1,-1.2,-1.3,-1.4,-1.5,-1.6,-1.7,-1.8,-1.9,-2.0,-2.5,-3.0,-3.5,-4.0,-4.5,-4.9]

In [32]:
len(xvalues)

26

In [33]:
reversed_list = list1[::-1]

In [34]:
y_values=np.array([reversed_list2])
y_values

array([[0.93939394, 0.9245283 , 0.95918367, 0.93406593, 0.92307692,
        0.93543956, 0.90212766, 0.89964158, 0.92351275, 0.92920354,
        0.93286219, 0.89933993, 0.92945545, 0.92511013, 0.89023336,
        0.91499654, 0.91399663, 0.8947619 , 0.88880944, 0.86509377,
        0.85005637, 0.80262914, 0.72350081, 0.56046654, 0.31872941,
        0.09302326]])

In [35]:
x_values=np.array([reversed_list])
x_values

array([[  33,   53,   98,  182,  351,  728,  235,  279,  353,  452,  566,
         606,  808,  908, 1157, 1447, 1779, 2100, 2797, 3306, 4435, 5401,
        6170, 6516,   86,   86]])

In [36]:
first = y_values*(1-y_values)
second = first/x_values
errors = np.sqrt(second)
errors

array([[0.04153603, 0.03628392, 0.01998733, 0.01839535, 0.01422308,
        0.00910805, 0.0193834 , 0.01798911, 0.01414584, 0.01206402,
        0.01051923, 0.01222234, 0.00900825, 0.00873505, 0.0091901 ,
        0.00733152, 0.00664725, 0.00669623, 0.00594418, 0.0059415 ,
        0.00536094, 0.00541579, 0.00569408, 0.00614866, 0.05024833,
        0.03132165]])

In [37]:
np.savetxt('NegativeYValuesRebin.out',y_values, delimiter=',')
np.savetxt('errorsNegativeRebin.out', errors, delimiter=',')