In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas import read_csv
import math
import seaborn as sns

In [2]:
df1 = pd.read_csv('/uscms/home/jieun201/nobackup/YOURWORKINGAREA/dec6_ds8/TestSetTruePT.csv')
df2 = pd.read_csv('predictionsFiles.csv')
df3 = pd.read_csv('true.csv')
df2.columns.values[0] = "predict"
df3.columns.values[0] = "true"
df2['predict'] = df2['predict'].astype(int)

In [3]:
concatenate = pd.concat([df1,df2, df3], axis=1)
concatenate

pt  predict  true
0      -2.627300        0     0
1       0.195180        2     2
2       1.338710        2     0
3       0.180981        2     2
4       0.457629        0     0
...          ...      ...   ...
163035  0.395177        2     0
163036 -0.164451        1     1
163037 -0.456705        1     0
163038 -0.168745        0     1
163039  0.124187        2     2

[163040 rows x 3 columns]

In [4]:
list1 = []
list2 = []

In [5]:
binValidate1 = concatenate.loc[(concatenate['pt'] < 0.1) & (concatenate['pt'] >= 0.0)]
list1.append(binValidate1.shape[0])
list2.append( sum((binValidate1.predict == 0))/(binValidate1.shape[0]) )

binValidate2 = concatenate.loc[(concatenate['pt'] < 0.2) & (concatenate['pt'] >= 0.1)]
list1.append(binValidate1.shape[0])
list2.append( sum((binValidate2.predict == 0))/(binValidate2.shape[0]) )

binValidate3 = concatenate.loc[(concatenate['pt'] < 0.3) & (concatenate['pt'] >= 0.2)]
list1.append( binValidate3.shape[0])
list2.append( sum((binValidate3.predict == 0))/(binValidate3.shape[0]) )

In [6]:
bin4 = concatenate.loc[  ((concatenate['pt'] < 0.4) & (concatenate['pt'] >= 0.3)  )       ]
list1.append(bin4.shape[0])
list2.append( sum((bin4.predict == 0))/(bin4.shape[0]))

In [7]:
bin5 = concatenate.loc[  ((concatenate['pt'] < 0.5) & (concatenate['pt'] >= 0.4)  )] 
list1.append(bin5.shape[0])
list2.append( sum((bin5.predict == 0))/(bin5.shape[0]))

In [8]:
#bin6 = concatenate.loc[  ((concatenate['pt'] < 0.6) & (concatenate['pt'] >= 0.5) ) | ( (concatenate['pt'] > -0.6) & (concatenate['pt'] <= -0.5)   )]
bin6 = concatenate.loc[(concatenate['pt'] < 0.6) & (concatenate['pt'] >= 0.5)]
list1.append(bin6.shape[0])
list2.append( sum((bin6.predict == 0))/(bin6.shape[0]) )

In [9]:
#bin7 = concatenate.loc[  ((concatenate['pt'] < 0.7) & (concatenate['pt'] >= 0.6) ) | ( (concatenate['pt'] > -0.7) & (concatenate['pt'] <= -0.6)   )] 
bin7 = concatenate.loc[(concatenate['pt'] < 0.7) & (concatenate['pt'] >= 0.6)]
list1.append(bin7.shape[0])
list2.append( sum((bin7.predict == 0))/(bin7.shape[0]) )

In [10]:
#bin8 = concatenate.loc[  ((concatenate['pt'] < 0.8) & (concatenate['pt'] >= 0.7) ) | ( (concatenate['pt'] > -0.8) & (concatenate['pt'] <= -0.7)    )]
bin8 = concatenate.loc[(concatenate['pt'] < 0.8) & (concatenate['pt'] >= 0.7)]
list1.append(bin8.shape[0])
list2.append( sum((bin8.predict == 0))/(bin8.shape[0]) )

In [11]:
#bin9 = concatenate.loc[  ((concatenate['pt'] < 0.9) & (concatenate['pt'] >= 0.8) ) | ( (concatenate['pt'] > -0.9) & (concatenate['pt'] <= -0.8)   )] 
bin9 = concatenate.loc[(concatenate['pt'] < 0.9) & (concatenate['pt'] >= 0.8)]
list1.append(bin9.shape[0])
list2.append( sum((bin9.predict == 0))/(bin9.shape[0]) )

In [12]:
#bin10 = concatenate.loc[  ((concatenate['pt'] < 1.0) & (concatenate['pt'] >= 0.9) ) | ( (concatenate['pt'] > -1.0) & (concatenate['pt'] <= -0.9)    )]
bin10 = concatenate.loc[(concatenate['pt'] < 1.0) & (concatenate['pt'] >= 0.9)]
list1.append(bin10.shape[0])
list2.append( sum((bin10.predict == 0))/(bin10.shape[0]) )

In [13]:
#bin11 = concatenate.loc[  ((concatenate['pt'] < 1.1) & (concatenate['pt'] >= 1.0) ) | ( (concatenate['pt'] > -1.1) & (concatenate['pt'] <= -1.0)    )]
bin11 = concatenate.loc[(concatenate['pt'] < 1.1) & (concatenate['pt'] >= 1.0)]
list1.append(bin11.shape[0])
list2.append( sum((bin11.predict == 0))/(bin11.shape[0]) )

In [14]:
#bin12 = concatenate.loc[  ((concatenate['pt'] < 1.2) & (concatenate['pt'] >= 1.1) ) | ( (concatenate['pt'] > -1.2) & (concatenate['pt'] <= -1.1)    )]
bin12 = concatenate.loc[(concatenate['pt'] < 1.2) & (concatenate['pt'] >= 1.1)]
list1.append(bin12.shape[0])
list2.append( sum((bin12.predict == 0))/(bin12.shape[0]) )

In [15]:
#bin13 = concatenate.loc[  ((concatenate['pt'] < 1.3) & (concatenate['pt'] >= 1.2) ) | ( (concatenate['pt'] > -1.3) & (concatenate['pt'] <= -1.2)    )]
bin13 = concatenate.loc[(concatenate['pt'] < 1.3) & (concatenate['pt'] >= 1.2)]
list1.append(bin13.shape[0])
list2.append( sum((bin13.predict == 0))/(bin13.shape[0]) )

In [16]:
#bin14 = concatenate.loc[  ((concatenate['pt'] < 1.4) & (concatenate['pt'] >= 1.3) ) | ( (concatenate['pt'] > -1.4) & (concatenate['pt'] <= -1.3)    )]
bin14 = concatenate.loc[(concatenate['pt'] < 1.4) & (concatenate['pt'] >= 1.3)]
list1.append(bin14.shape[0])
list2.append( sum((bin14.predict == 0))/(bin14.shape[0]) )

In [17]:
#bin15 = concatenate.loc[  ((concatenate['pt'] < 1.5) & (concatenate['pt'] >= 1.4) ) | ( (concatenate['pt'] > -1.5) & (concatenate['pt'] <= -1.4)   )] 
bin15 = concatenate.loc[(concatenate['pt'] < 1.5) & (concatenate['pt'] >= 1.4)]
list1.append(bin15.shape[0])
list2.append( sum((bin15.predict == 0))/(bin15.shape[0]) )

In [18]:
#bin16 = concatenate.loc[  ((concatenate['pt'] < 1.6) & (concatenate['pt'] >= 1.5) ) | ( (concatenate['pt'] > -1.6) & (concatenate['pt'] <= -1.5)   )] 
bin16 = concatenate.loc[(concatenate['pt'] < 1.6) & (concatenate['pt'] >= 1.5)]
list1.append(bin16.shape[0])
list2.append( sum((bin16.predict == 0))/(bin16.shape[0]) )

In [19]:
#bin17 = concatenate.loc[  ((concatenate['pt'] < 1.7) & (concatenate['pt'] >= 1.6) ) | ( (concatenate['pt'] > -1.7) & (concatenate['pt'] <= -1.6)    )]
bin17 = concatenate.loc[(concatenate['pt'] < 1.7) & (concatenate['pt'] >= 1.6)]
list1.append(bin17.shape[0])
list2.append( sum((bin17.predict == 0))/(bin17.shape[0]) )

In [20]:
#bin18 = concatenate.loc[  ((concatenate['pt'] < 1.8) & (concatenate['pt'] >= 1.7) ) | ( (concatenate['pt'] > -1.8) & (concatenate['pt'] <= -1.7)    )]
bin18 = concatenate.loc[(concatenate['pt'] < 1.8) & (concatenate['pt'] >= 1.7)]
list1.append(bin18.shape[0])
list2.append( sum((bin18.predict == 0))/(bin18.shape[0]) )

In [21]:
#bin19 = concatenate.loc[  ((concatenate['pt'] < 1.9) & (concatenate['pt'] >= 1.8) ) | ( (concatenate['pt'] > -1.9) & (concatenate['pt'] <= -1.8)   )] 
bin19 = concatenate.loc[(concatenate['pt'] < 1.9) & (concatenate['pt'] >= 1.8)]
list1.append(bin19.shape[0])
list2.append( sum((bin19.predict == 0))/(bin19.shape[0]) )

In [22]:
#bin20 = concatenate.loc[  ((concatenate['pt'] < 2.0) & (concatenate['pt'] >= 1.9) ) | ( (concatenate['pt'] > -2.0) & (concatenate['pt'] <= -1.9)    )]
bin20 = concatenate.loc[(concatenate['pt'] < 2.0) & (concatenate['pt'] >= 1.9)]
list1.append(bin20.shape[0])
list2.append( sum((bin20.predict == 0))/(bin20.shape[0]) )

In [23]:
bin21 = concatenate.loc[(concatenate['pt'] < 2.1) & (concatenate['pt'] >= 2.0)]
bin22 = concatenate.loc[(concatenate['pt'] < 2.2) & (concatenate['pt'] >= 2.1)]
bin23 = concatenate.loc[(concatenate['pt'] < 2.3) & (concatenate['pt'] >= 2.2)]
bin24 = concatenate.loc[(concatenate['pt'] < 2.4) & (concatenate['pt'] >= 2.3)]
bin25 = concatenate.loc[(concatenate['pt'] < 2.5) & (concatenate['pt'] >= 2.4)]

bin21_25 = bin21.shape[0] + bin22.shape[0]+ bin23.shape[0] + bin24.shape[0]+ bin25.shape[0]
list1.append(bin21_25)
list2.append((sum(bin21.predict == 0) +sum(bin22.predict == 0) + sum(bin23.predict == 0) + sum(bin24.predict == 0) + sum(bin25.predict == 0))/bin21_25) 

In [24]:
bin26 = concatenate.loc[(concatenate['pt'] < 2.6) & (concatenate['pt'] >= 2.5)]
bin27 = concatenate.loc[(concatenate['pt'] < 2.7) & (concatenate['pt'] >= 2.6)]
bin28 = concatenate.loc[(concatenate['pt'] < 2.8) & (concatenate['pt'] >= 2.7)]
bin29 = concatenate.loc[(concatenate['pt'] < 2.9) & (concatenate['pt'] >= 2.8)]
bin30 = concatenate.loc[(concatenate['pt'] < 3.0) & (concatenate['pt'] >= 2.9)]

bin26_30 = bin26.shape[0] + bin27.shape[0]+ bin28.shape[0] + bin29.shape[0]+ bin30.shape[0]
list1.append(bin26_30)
list2.append((sum(bin26.predict == 0) +sum(bin27.predict == 0) + sum(bin28.predict == 0) + sum(bin29.predict == 0) + sum(bin30.predict == 0))/bin26_30) 

In [25]:
bin31 = concatenate.loc[(concatenate['pt'] < 3.1) & (concatenate['pt'] >= 3.0)]
bin32 = concatenate.loc[(concatenate['pt'] < 3.2) & (concatenate['pt'] >= 3.1)]
bin33 = concatenate.loc[(concatenate['pt'] < 3.3) & (concatenate['pt'] >= 3.2)]
bin34 = concatenate.loc[(concatenate['pt'] < 3.4) & (concatenate['pt'] >= 3.3)]
bin35 = concatenate.loc[(concatenate['pt'] < 3.5) & (concatenate['pt'] >= 3.4)]
bin31_35 = bin31.shape[0] + bin32.shape[0]+ bin33.shape[0] + bin34.shape[0]+ bin35.shape[0]
list1.append(bin31_35)
list2.append((sum(bin31.predict == 0) +sum(bin32.predict == 0) + sum(bin33.predict == 0) + sum(bin34.predict == 0) + sum(bin35.predict == 0))/bin31_35 ) 

In [26]:
bin36 = concatenate.loc[(concatenate['pt'] < 3.6) & (concatenate['pt'] >= 3.5)]
bin37 = concatenate.loc[(concatenate['pt'] < 3.7) & (concatenate['pt'] >= 3.6)]
bin38 = concatenate.loc[(concatenate['pt'] < 3.8) & (concatenate['pt'] >= 3.7)]
bin39 = concatenate.loc[(concatenate['pt'] < 3.9) & (concatenate['pt'] >= 3.8)]
bin40 = concatenate.loc[(concatenate['pt'] < 4.0) & (concatenate['pt'] >= 3.9)]
bin36_40 = bin36.shape[0] + bin37.shape[0]+ bin38.shape[0] + bin39.shape[0]+ bin40.shape[0]
list1.append(bin36_40)
list2.append((sum(bin36.predict == 0) +sum(bin37.predict == 0) + sum(bin38.predict == 0) + sum(bin39.predict == 0) + sum(bin40.predict == 0))/bin36_40 ) 

In [27]:
bin41 = concatenate.loc[(concatenate['pt'] < 4.1) & (concatenate['pt'] >= 4.0)]
bin42 = concatenate.loc[(concatenate['pt'] < 4.2) & (concatenate['pt'] >= 4.1)]
bin43 = concatenate.loc[(concatenate['pt'] < 4.3) & (concatenate['pt'] >= 4.2)]
bin44 = concatenate.loc[(concatenate['pt'] < 4.4) & (concatenate['pt'] >= 4.3)]
bin45 = concatenate.loc[(concatenate['pt'] < 4.5) & (concatenate['pt'] >= 4.4)]
bin41_45 = bin41.shape[0] + bin42.shape[0]+ bin43.shape[0] + bin44.shape[0]+ bin45.shape[0] 
list1.append(bin41_45)
list2.append((sum(bin41.predict == 0) +sum(bin42.predict == 0) + sum(bin43.predict == 0) + sum(bin44.predict == 0) + sum(bin45.predict == 0))/bin41_45 ) 

In [28]:
bin46 = concatenate.loc[(concatenate['pt'] < 4.6) & (concatenate['pt'] >= 4.5)]
bin47 = concatenate.loc[(concatenate['pt'] < 4.7) & (concatenate['pt'] >= 4.6)]
bin48 = concatenate.loc[(concatenate['pt'] < 4.8) & (concatenate['pt'] >= 4.7)]
bin49 = concatenate.loc[(concatenate['pt'] < 4.9) & (concatenate['pt'] >= 4.8)]
bin50 = concatenate.loc[(concatenate['pt'] < 5.0) & (concatenate['pt'] >= 4.9)]
bin46_50 = bin46.shape[0] + bin47.shape[0]+ bin48.shape[0] + bin49.shape[0]+ bin50.shape[0]  
list1.append(bin46_50)
list2.append((sum(bin46.predict == 0) +sum(bin47.predict == 0) + sum(bin48.predict == 0) + sum(bin49.predict == 0) + sum(bin50.predict == 0))/bin46_50 ) 

In [29]:
len(list2)

26

In [30]:
y_values=np.array([list2])
y_values

array([[0.02439024, 0.21151482, 0.45764987, 0.66193004, 0.76871633,
        0.82520325, 0.86097202, 0.88631427, 0.88607595, 0.88914156,
        0.89541547, 0.90382903, 0.91390728, 0.90909091, 0.91147541,
        0.92929293, 0.91176471, 0.93123209, 0.90429043, 0.89370079,
        0.93562232, 0.92375367, 0.91666667, 0.93548387, 0.93333333,
        0.93548387]])

In [31]:
x_values=np.array([list1])
x_values

array([[  82,   82, 6706, 6404, 5383, 4182, 3395, 2762, 2133, 1759, 1396,
        1123,  906,  781,  610,  495,  442,  349,  303,  254,  699,  341,
         168,   93,   45,   31]])

In [32]:
first = y_values*(1-y_values)
second = first/x_values
errors = np.sqrt(second)
errors

array([[0.01703489, 0.04509831, 0.0060838 , 0.00591131, 0.00574703,
        0.00587293, 0.0059378 , 0.00603997, 0.00687936, 0.00748578,
        0.00819037, 0.00879782, 0.00931902, 0.01028684, 0.0115011 ,
        0.0115214 , 0.01349123, 0.01354594, 0.01690092, 0.01933946,
        0.00928281, 0.01437177, 0.0213236 , 0.0254748 , 0.03718489,
        0.04412365]])

In [33]:
np.savetxt('PositiveYValuesRebin.out',y_values, delimiter=',')
np.savetxt('errorsPositiveRebin.out', errors, delimiter=',')